# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scrapebook',
                'doc_host': 'https://imbrem.github.io',
                'git_url': 'https://github.com/imbrem/scrapebook',
                'lib_path': 'scrapebook'},
  'syms': {'scrapebook.core': {'scrapebook.core.say_hello': ('core.html#say_hello', 'scrapebook/core.py')}}}
